### PR TITLE
Fix TypeError and TensorFlow naming convention.

### PR DESCRIPTION
**Pull request by maxisme**

### CODE REVIEW

**Comment by lucasb-eyer** [comment]
1. Since `keep_dims=False` is the same as not passing it in the first place, we should rather do that, so as to stay compatible with more TF versions. Could you do that instead please?

2. I don't remember seeing that TypeError, is this new? Which TF version? In any case, could you change that to `tf.float32`, so we don't destroy performance if TF decides to run it on GPU?

Thanks!

**Comment by maxisme** [comment]
Using `1.7.0`

**Comment by lucasb-eyer** [comment]
Thank you! I'll try it out over here and merge if it works.

**Comment by lucasb-eyer** [comment]
Sorry, lost track of it. Just checked that it works, so merging, thank you!

**Comment by maxisme** [comment]
Strangely I am now getting the error:

```
Traceback (most recent call last):
  File "/var/www/idmy.team/python/train_feature_extractor.py", line 154, in <module>
    endpoints, body_prefix = model.endpoints(images, is_training=True)
  File "/var/www/idmy.team/python/train/resnet_v1_50.py", line 11, in endpoints
    image = image - tf.constant(_RGB_MEAN, dtype=tf.float32, shape=(1,1,1,3))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 962, in binary_op_wrapper
    y = ops.convert_to_tensor(y, dtype=x.dtype.base_dtype, name="y")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 950, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1040, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 883, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype uint8 for Tensor with dtype float32: 'Tensor("Const:0", shape=(1, 1, 1, 3), dtype=float32)'
```

with the same TF version.

**Pull request merged**
